services:
  minimal-portfolio-template:
    container_name: minimal-portfolio-template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
